# Generated by Django 5.1.4 on 2025-01-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_message_remove_membership_community_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="media",
            new_name="image",
        ),
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="post_videos/"),
        ),
    ]
